#pragma config(Motor,  port2,            frontRightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port3,            frontLeftMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port4,            backRightMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port5,           backLeftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
// Here, each of the motors are initialized and configured.
// Notice how the names that each motor is binded to is used later in the code.

// This is the main task - everything inside here runs when the robot starts.
task main(){
	// This is a crude infinite loop - everything inside the while loop is repeated forever.
	while (1 == 1){
		motor[frontRightMotor] = -vexRT[Ch2]; // binds the front right motor to the third joystick channel
		motor[backRightMotor] = -vexRT[Ch2]; // binds the back right motor to the third joystick channel
		motor[frontLeftMotor] = -vexRT[Ch3]; // binds the front left motor to the second joystick channel
		motor[backLeftMotor] = -vexRT[Ch3]; // binds the back left motor to the second joystick channel
	}
}
